Repository Frelya/react-site-editor, pull requests merged in 2023-02, with the labels that each got.

#10 Setup `eslint` and `prettier`
  .eslintrc.yaml
  .eslintrc.yml
  .prettierrc
  .prettierrc.yaml
  README.md
  apps/frontend/package.json
  apps/frontend/src/App.tsx
  apps/frontend/src/main.tsx
  apps/frontend/tailwind.config.cjs
  apps/frontend/tsconfig.json
  apps/frontend/tsconfig.node.json
  apps/frontend/vite.config.ts
  package.json
  packages/functions/index.ts
  packages/functions/package.json
  packages/types/index.ts
  packages/types/package.json
  packages/ui/package.json
  packages/ui/src/App.css
  packages/ui/src/App.tsx
  packages/ui/src/index.css
  packages/ui/src/main.tsx
  packages/ui/tsconfig.json
  packages/ui/tsconfig.node.json
  packages/ui/vite.config.ts
Labels: configuration

#12 Add a `Format` and `Lint` actions
  .github/workflows/format.yaml
  .github/workflows/lint.yaml
  packages/ui/src/App.tsx
Labels: configuration

#17 Add a global layout to start
  .eslintrc.yaml
  apps/frontend/index.html
  apps/frontend/package.json
  apps/frontend/src/App.tsx
  apps/frontend/src/components/ComponentWrapper/ComponentWrapper.module.css
  apps/frontend/src/components/ComponentWrapper/ComponentWrapper.tsx
  apps/frontend/src/components/SideBar/SideBar.module.css
  apps/frontend/src/components/SideBar/SideBar.tsx
  apps/frontend/src/components/SideBarHeader/SideBarHeader.module.css
  apps/frontend/src/components/SideBarHeader/SideBarHeader.tsx
  apps/frontend/src/index.css
  apps/frontend/src/main.tsx
  apps/frontend/src/pages/EditorPage/EditorPage.module.css
  apps/frontend/src/pages/EditorPage/EditorPage.tsx
  apps/frontend/src/pages/HomePage/HomePage.tsx
  apps/frontend/vite.config.ts
  packages/types/index.ts
  packages/ui/src/components/Button.tsx
  packages/ui/src/main.tsx
Labels: frontend, feature

#22 epoundor/vite resolve alias
  apps/frontend/src/views/EditorPage/EditorPage.tsx
  apps/frontend/vite.config.ts
Labels: configuration

#23 Epoundor/dragndrop
  apps/frontend/index.html
  apps/frontend/src/components/Decorator/Draggable.tsx
  apps/frontend/src/components/Decorator/Dropable.tsx
  apps/frontend/src/routes/routes.tsx
  apps/frontend/src/views/EditorPage/EditorPage.tsx
  apps/frontend/src/views/Preview/Preview.module.css
  apps/frontend/src/views/Preview/Preview.tsx
  apps/frontend/vite.config.ts
  packages/types/index.ts
Labels: frontend, feature

#27 Rewrite all styles using `tailwindcss`
  apps/frontend/src/components/ComponentWrapper/ComponentWrapper.module.css
  apps/frontend/src/components/Preview/PreviewIframe/PreviewIframe.module.css
  apps/frontend/src/components/Preview/PreviewIframe/PreviewIframe.tsx
  apps/frontend/src/components/SideBar/SideBar.module.css
  apps/frontend/src/components/SideBarHeader/SideBarHeader.module.css
  apps/frontend/src/main.css
  apps/frontend/src/views/EditorPage/EditorPage.module.css
  apps/frontend/src/views/HomePage/HomePage.module.css
  apps/frontend/src/views/Preview/Preview.module.css
  apps/frontend/src/views/Preview/Preview.tsx
Labels: enhancement

#28 Add reactivity to the Sidebar
  apps/frontend/postcss.config.cjs
  apps/frontend/src/assets/icons/chevron-left.svg
  apps/frontend/src/assets/icons/xmark.svg
  apps/frontend/src/components/ComponentWrapper/ComponentWrapper.module.css
  apps/frontend/src/components/ComponentsList/ComponentsList.module.css
  apps/frontend/src/components/ComponentsList/ComponentsList.tsx
  apps/frontend/src/components/Decorators/Draggable.tsx
  apps/frontend/src/components/Decorators/Icon.tsx
  apps/frontend/src/components/Preview/PreviewIframe/PreviewIframe.module.css
  apps/frontend/src/components/Preview/PreviewIframe/PreviewIframe.tsx
  apps/frontend/src/components/PropertiesComponents/SizeProperty/SizeProperty.module.css
  apps/frontend/src/components/PropertiesComponents/SizeProperty/SizeProperty.tsx
  apps/frontend/src/components/PropertiesComponents/TextProperty/TextProperty.module.css
  apps/frontend/src/components/PropertiesComponents/TextProperty/TextProperty.tsx
  apps/frontend/src/components/SideBar/SideBar.module.css
  apps/frontend/src/components/SideBar/SideBar.tsx
  apps/frontend/src/components/SideBarHeader/SideBarHeader.module.css
  apps/frontend/src/components/SideBarRight/SideBarRight.module.css
  apps/frontend/src/components/SideBarRight/SideBarRight.tsx
  apps/frontend/src/views/EditorPage/EditorPage.module.css
  apps/frontend/src/views/EditorPage/EditorPage.tsx
  apps/frontend/tailwind.config.cjs
  packages/functions/findAllReactComponent.ts
  packages/functions/index.ts
  packages/functions/innerContentOfHtmlDiv.ts
  packages/types/index.ts
  packages/ui/postcss.config.cjs
  packages/ui/src/components/Button/Button.module.css
  packages/ui/src/components/Button/Button.tsx
  packages/ui/tailwind.config.cjs
Labels: enhancement, frontend, feature

#25 Add `Storage` hooks
  apps/frontend/src/hooks/useLocalStorage.ts
  apps/frontend/src/hooks/useSessionStorage.ts
  apps/frontend/src/hooks/useStorage.ts
  apps/frontend/vite.config.ts
  packages/functions/index.ts
Labels: feature

#31 Epoundor/icons
  apps/frontend/package.json
  apps/frontend/src/components/ComponentsList/ComponentsList.tsx
  apps/frontend/src/components/Icons/AllIcons/ChevronLeft.tsx
  apps/frontend/src/components/Icons/Icon.tsx
  apps/frontend/src/components/PropertiesComponents/SizeProperty/SizeProperty.tsx
  apps/frontend/src/components/PropertiesComponents/TextProperty/TextProperty.tsx
  apps/frontend/src/components/SideBarRight/SideBarRight.tsx
  apps/frontend/src/views/EditorPage/EditorPage.tsx
  packages/functions/index.ts
  packages/functions/kebabToPascal.ts
  packages/types/index.ts
  packages/ui/src/components/Button/Button.tsx
  packages/ui/src/main.tsx
Labels: frontend

#36 Epoundor/proposal
  apps/frontend/package.json
  apps/frontend/scripts/getAvailableIcons.ts
  apps/frontend/src/components/Icons/AllIcons/XMark.tsx
  apps/frontend/src/components/Icons/AvailableIcons.ts
  apps/frontend/src/components/Icons/Icon.tsx
  apps/frontend/src/views/EditorPage/EditorPage.tsx
  apps/frontend/tsconfig.json
  package-lock.json
  package.json
  packages/functions/index.ts
  packages/functions/pascalToKebab.ts
Labels: enhancement

#35 `Icon` use now `AvailableIcons` type to auto-complete name field
  .gitignore
  apps/frontend/libs/getAvailableIcons.ts
Labels: frontend, configuration
